name: Generate Root SSL Certificate

on:
  workflow_dispatch:
    inputs:
      regenerate:
        description: 'Force regenerate certificate'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  generate-root-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Check existing certificate
        id: check-cert
        run: |
          if [ -f "root-ca.key" ] && [ -f "root-ca.crt" ] && [ "${{ github.event.inputs.regenerate }}" == "false" ]; then
            echo "Certificate already exists. Skipping generation."
            echo "::set-output name=generate::false"
          else
            echo "::set-output name=generate::true"
          fi

      - name: Generate Root CA
        if: steps.check-cert.outputs.generate == 'true'
        run: |
          # Generate Root CA Private Key
          openssl genrsa -out root-ca.key 4096

          # Generate Root CA Certificate
          openssl req -x509 -new -nodes \
            -key root-ca.key \
            -sha256 \
            -days 3650 \
            -subj "/C=US/ST=California/L=San Francisco/O=MITMRoot/OU=RootCA/CN=MITMRootCA" \
            -out root-ca.crt

      - name: Generate Intermediate CA
        if: steps.check-cert.outputs.generate == 'true'
        run: |
          # Generate Intermediate CA Private Key
          openssl genrsa -out intermediate-ca.key 4096

          # Generate Intermediate CA CSR
          openssl req -new -key intermediate-ca.key \
            -subj "/C=US/ST=California/L=San Francisco/O=MITMIntermediate/OU=IntermediateCA/CN=MITMIntermediateCA" \
            -out intermediate-ca.csr

          # Sign Intermediate CA with Root CA
          openssl x509 -req -in intermediate-ca.csr \
            -CA root-ca.crt \
            -CAkey root-ca.key \
            -CAcreateserial \
            -out intermediate-ca.crt \
            -days 3650 \
            -sha256

      - name: Create README
        run: |
          echo "# Root SSL Certificate for MITM

          ## Certificate Details
          - Root CA Key: \`root-ca.key\`
          - Root CA Certificate: \`root-ca.crt\`
          - Intermediate CA Key: \`intermediate-ca.key\`
          - Intermediate CA Certificate: \`intermediate-ca.crt\`

          ### Usage Warning
          These certificates are generated for testing and MITM purposes.
          Do not use in production environments without proper security considerations.
          " > CERT_README.md

      - name: Commit Certificates
        run: |
          git config --global user.name 'Certificate Generator'
          git config --global user.email 'action@github.com'
          git add root-ca.key root-ca.crt intermediate-ca.key intermediate-ca.crt CERT_README.md
          git commit -m "Generate Root and Intermediate SSL Certificates"
          git push

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ssl-certificates
          path: |
            root-ca.key
            root-ca.crt
            intermediate-ca.key
            intermediate-ca.crt
          retention-days: 5
